### ISSUE TITLE
[bug]: Auth is currently broken

### ISSUE THREAD

**Issue by asim** [quran/quran.com-frontend-next#2011]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

I was previously logged into the website but then my bookmarks stopped appearing. It said I was still logged in but when I tried logging out nothing happened. I cleared my cookies and tried to reauthenticate but received an error with "too many requests" https://auth.quran.com/auth/google. Please can you take a look. 

### Steps to reproduce

Try login via Google oauth.

### Environment (please complete the following information) and Add any other context about this bug

Chrome 

### Environment

Production(quran.com)

**Comment by osamasayed** [comment]
Alsamau Alikum @asim, This is not a bug, it's by design. As the error indicates, your IP has been blocked due to too many requests within a short period of time. May I know which actions were you performing that led you to getting rate-limited?

**Comment by deeseeker** [comment]
@osamasayed can we close this issue since it has been resolved to limit our issue stats?

**Comment by asim** [comment]
Was it resolved? I still face this issue. I have to come off my wifi just to log in.

**Comment by deeseeker** [comment]
> Was it resolved? I still face this issue. I have to come off my wifi just to log in.

I am unable to reproduce the error you described. it's likely a design issue as @osamasayed mentioned. Below is a screenshot of my attempt to reproduce the issue. So, if it's not a bug, I think we should close it down to free the issue stats.
![Screenshot 2024-09-16 205706](https://github.com/user-attachments/assets/33c767ac-df17-4e76-977f-58f05c91770f)
